# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01-intro-tutorial-by-jeremy/part2.ipynb.

# %% auto 0
__all__ = ['app', 'rt', 'get']

# %% ../../nbs/01-intro-tutorial-by-jeremy/part2.ipynb 1
from fasthtml.common import *

# %% ../../nbs/01-intro-tutorial-by-jeremy/part2.ipynb 4
app, rt = fast_app(live=True)

# %% ../../nbs/01-intro-tutorial-by-jeremy/part2.ipynb 9
@rt("/")
def get():
    return Titled("Greeting", Div(P("Hello  World!")), P(A("Link", href="/change")))

# %% ../../nbs/01-intro-tutorial-by-jeremy/part2.ipynb 11
@rt("/change")
def get():
    return Titled("Change", Div(P("Change is good!")), P(A("Back", href="/")))

# %% ../../nbs/01-intro-tutorial-by-jeremy/part2.ipynb 19
serve()
