# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01-intro-tutorial-by-jeremy/part4.ipynb.

# %% auto 0
__all__ = ['app', 'rt', 'todos', 'Todo', 'render', 'mk_input', 'get', 'post', 'delete']

# %% ../../nbs/01-intro-tutorial-by-jeremy/part4.ipynb 1
from fasthtml.common import *

# %% ../../nbs/01-intro-tutorial-by-jeremy/part4.ipynb 26
def render(todo):
    tid = f"todo-{todo.id}"
    toggle = A("Toggle", hx_get=f"/toggle/{todo.id}", target_id=tid)
    delete = A("Delete", hx_delete=f"/{todo.id}", target_id=tid, hx_swap="outerHTML")
    return Li(
        toggle,
        delete,
        todo.title + ("✅ " if todo.done else ""),
        id=tid,
    )


app, rt, todos, Todo = fast_app(
    "data/todos.db",
    live=True,
    render=render,
    id=int,
    title=str,
    done=bool,
    pk="id",
)

# %% ../../nbs/01-intro-tutorial-by-jeremy/part4.ipynb 39
def mk_input():
    return Input(placeholder="Add a new todo", id="title", hx_swap_oob="true")

# %% ../../nbs/01-intro-tutorial-by-jeremy/part4.ipynb 40
@rt("/")
def get():
    frm = Form(
        Group(mk_input(), Button("Add")),
        hx_post="/",
        target_id="todo-list",
        hx_swap="beforeend",
    )
    return Titled(
        "Todos",
        Card(
            Ul(*todos(), id="todo-list"),
            header=frm,
        ),
    )

# %% ../../nbs/01-intro-tutorial-by-jeremy/part4.ipynb 41
@rt("/")
def post(todo: Todo):
    return todos.insert(todo), mk_input()

# %% ../../nbs/01-intro-tutorial-by-jeremy/part4.ipynb 42
@rt("/{tid}")
def delete(tid: int):
    todos.delete(tid)


@rt("/toggle/{tid}")
def get(tid: int):
    todo = todos[tid]
    todo.done = not todo.done
    return todos.update(todo)

# %% ../../nbs/01-intro-tutorial-by-jeremy/part4.ipynb 45
serve()
