# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fasthtml-tutorials',
                'doc_host': 'https://siraj-samsudeen.github.io',
                'git_url': 'https://github.com/siraj-samsudeen/fasthtml-tutorials',
                'lib_path': 'fasthtml_tutorials'},
  'syms': { 'fasthtml_tutorials.01-intro-tutorial-by-jeremy.part1': { 'fasthtml_tutorials.01-intro-tutorial-by-jeremy.part1.get': ( '01-intro-tutorial-by-jeremy/part1.html#get',
                                                                                                                                    'fasthtml_tutorials/01-intro-tutorial-by-jeremy/part1.py')},
            'fasthtml_tutorials.01-intro-tutorial-by-jeremy.part2': { 'fasthtml_tutorials.01-intro-tutorial-by-jeremy.part2.get': ( '01-intro-tutorial-by-jeremy/part2.html#get',
                                                                                                                                    'fasthtml_tutorials/01-intro-tutorial-by-jeremy/part2.py')},
            'fasthtml_tutorials.01-intro-tutorial-by-jeremy.part3': { 'fasthtml_tutorials.01-intro-tutorial-by-jeremy.part3.NumList': ( '01-intro-tutorial-by-jeremy/part3.html#numlist',
                                                                                                                                        'fasthtml_tutorials/01-intro-tutorial-by-jeremy/part3.py'),
                                                                      'fasthtml_tutorials.01-intro-tutorial-by-jeremy.part3.get': ( '01-intro-tutorial-by-jeremy/part3.html#get',
                                                                                                                                    'fasthtml_tutorials/01-intro-tutorial-by-jeremy/part3.py')},
            'fasthtml_tutorials.core': { 'fasthtml_tutorials.core.show_with_pico': ( 'core.html#show_with_pico',
                                                                                     'fasthtml_tutorials/core.py'),
                                         'fasthtml_tutorials.core.start_server': ('core.html#start_server', 'fasthtml_tutorials/core.py'),
                                         'fasthtml_tutorials.core.stop_server': ('core.html#stop_server', 'fasthtml_tutorials/core.py')}}}
