# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fasthtml-tutorials',
                'doc_host': 'https://siraj-samsudeen.github.io',
                'git_url': 'https://github.com/siraj-samsudeen/fasthtml-tutorials',
                'lib_path': 'fasthtml_tutorials'},
  'syms': {'fasthtml_tutorials.core': {'fasthtml_tutorials.core.foo': ('core.html#foo', 'fasthtml_tutorials/core.py')}}}
