# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01-intro-tutorial-by-jeremy/part1.ipynb.

# %% auto 0
__all__ = ['app', 'rt', 'get']

# %% ../nbs/01-intro-tutorial-by-jeremy/part1.ipynb 1
from fasthtml.common import *

# %% ../nbs/01-intro-tutorial-by-jeremy/part1.ipynb 4
app, rt = fast_app()

# %% ../nbs/01-intro-tutorial-by-jeremy/part1.ipynb 14
@rt("/")
def get():
    return Titled("Greeting", Div(P("Hello  World!")))

# %% ../nbs/01-intro-tutorial-by-jeremy/part1.ipynb 18
serve()
